name: Build and Test
on: pull_request

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    name: Build and Test
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine modified files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            relevant_files:
              - '.github/workflows/test.yml'
              - 'code/code/**.cc'
              - 'code/code/**.h'
              - 'code/code/**.cpp'
              - 'code/code/**.hpp'

      - name: Install dependencies and compile
        if: steps.filter.outputs.relevant_files == 'true'
        run: |
          sudo apt-get update &&
          sudo apt-get install --yes --no-install-recommends build-essential libboost-dev libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libboost-system-dev libmariadbclient-dev scons libcurl4-openssl-dev &&
          scons -C code -j`nproc` -Q pretty=0 debug=1 sanitize=1 olevel=2 sneezy
