name: Validate PR
on: pull_request

jobs:
  maybe_compile:
    runs-on: ubuntu-20.04
    name: Ensure Successful Compilation
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine if the PR modifies any source files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            source_files_modified:
              - 'code/code/**.cc'
              - 'code/code/**.h'
              - 'code/code/**.cpp'
              - 'code/code/**.hpp'

      - name: If yes, install dependencies and compile
        if: steps.filter.outputs.source_files_modified == 'true'
        run: |
          sudo apt-get update &&
          sudo apt-get install --yes --no-install-recommends build-essential libboost-dev libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libboost-system-dev libmariadbclient-dev scons libcurl4-openssl-dev &&
          scons -C code -j`nproc` -Q pretty=0 debug=1 sanitize=1 olevel=2 sneezy
