name: Build and Test
on: pull_request

jobs:
  always_pass:
    # This job exists to make sure that this workflow will run and automatically pass
    # when the 'build and test' job is skipped when the pull request doesn't change
    # any code or the test.yml workflow itself. Without this, PRs will be blocked and
    # unmergeable.
    runs-on: ubuntu-20.04
    steps:
      - name: Always pass
        run: echo "Running Build and Test workflow."

  build_and_test:
    runs-on: ubuntu-20.04
    name: Build and Test
    if: >-
      contains(toJSON(github.event.pull_request.changed_files), 'code/code') ||
      contains(toJSON(github.event.pull_request.changed_files), '.github/workflows/test.yml')
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: sudo apt-get update
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-get update
      - run: sudo apt-get install --yes --no-install-recommends build-essential libboost-dev libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libboost-system-dev libmariadbclient-dev scons libcurl4-openssl-dev
      - run: scons -C code -j`nproc` -Q pretty=0 debug=1 sanitize=1 olevel=2 sneezy
