name: Validate PR
on: pull_request

jobs:
  compile_and_run_game:
    runs-on: ubuntu-latest
    name: Compile and Run Game
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          set -e
          sudo apt-get update
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install --yes --no-install-recommends g++-9 build-essential libboost-dev libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libboost-system-dev libmariadb-dev scons libcurl4-openssl-dev ca-certificates mariadb-server

      - name: Verify, configure, and seed a test database
        run: |
          set -e
          sudo systemctl is-active --quiet mariadb || sudo systemctl start mariadb
          sudo mariadb -e "create database sneezy; create database immortal;"
          sudo mariadb -e "create user 'runner'@'localhost'; grant all on sneezy.* to 'runner'@'localhost'; grant all on immortal.* to 'runner'@'localhost';"
          for db in immortal sneezy ; do
            for phase in tables views data ; do
              [ -d "_Setup-data/sql_$phase/$db" ] || continue
              for sql in _Setup-data/sql_$phase/$db/*.sql ; do
                echo "loading '$sql'"
                mysql $db < $sql
              done
            done
          done

      - name: Restore cached compilation results
        uses: actions/cache/restore@v4
        with:
          path: |
            code/.sconsign.dblite
            code/objs          
          restore-keys: |
            ${{ runner.os }}-scons-

      - name: Perform incremental compilation using cached results from previous workflow
        run: |
          scons -C code -j`nproc` CXX=g++-9 pretty=1 debug=1 sanitize=1 olevel=0 sneezy

      - name: Cache new compilation results
        uses: actions/cache/save@v4
        with:
          path: |
            code/.sconsign.dblite
            code/objs
            !code/objs/libsneezy.a
            !code/objs/sneezy
          key: ${{ runner.os }}-scons-${{ hashFiles('code/code/**.cc', 'code/code/**.h') }}

      - name: Verify the game boots up successfully
        run: |
          set -e
          ./code/sneezy 2>&1 | tee output.log &
          SNEEZY_PID=$!
          while kill -0 $SNEEZY_PID ; do
            if tail -n 100 output.log | grep -q "Entering game loop." ; then
              echo "Sneezy started successfully"
              exit 0
            fi
            sleep 1
          done
          echo "Sneezy process crashed"
          exit 1
